Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,11 @@ jobs:
       - uses: actions/checkout@v2
       - run: |
           URL=$(curl -s "https://api.github.com/repos/YTLitePlus/YTLitePlus/releases/latest" | jq -r '.assets[0].browser_download_url')
-          curl -L -o ./YTLitePlus.ipa $URL
+          curl -L -o ./YTLitePlus.ipa $URL || exit 0
+          if [ ! -f "./YTLitePlus.ipa" ]; then
+            echo "File not found, exiting"
+            exit 0
+          fi
           RID=$(curl -sH "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" https://api.github.com/repos/EscapeAltDelete/Updater/releases/tags/YTLitePlus | jq -r '.id')
           curl -X DELETE -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' https://api.github.com/repos/EscapeAltDelete/Updater/releases/$RID
       - uses: ncipollo/release-action@v1
