Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,16 +15,28 @@ jobs:
         id: latest
         run: |
           LATEST=$(curl --silent "https://api.github.com/repos/YTLitePlus/YTLitePlus/releases/latest" | jq -r .tag_name)
+          if [ "$LATEST" == "null" ]; then
+            echo "Latest release not found"
+            exit 1
+          fi
           echo "version=$LATEST" >> $GITHUB_ENV
 
       - name: Download release asset
         run: |
           ASSET_URL=$(curl --silent "https://api.github.com/repos/YTLitePlus/YTLitePlus/releases/latest" | jq -r '.assets[0].browser_download_url')
+          if [ "$ASSET_URL" == "null" ]; then
+            echo "Asset URL not found"
+            exit 1
+          fi
           curl -L -o ./assets/ytliteplus.ipa $ASSET_URL
 
       - name: Delete old release
         run: |
           RELEASE_ID=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/tags/YTLitePlus" | jq -r '.id')
+          if [ "$RELEASE_ID" == "null" ]; then
+            echo "Release ID not found"
+            exit 1
+          fi
           curl -X DELETE "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID" -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}"
 
       - name: Create new release
